spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopper
    username: postgres
    password: postgres

  jackson:
    serialization:
      indent-output: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#  mail:
#    host: localhost
#    port: 1025
#    username: admin
#    password: admin
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

server:
  error:
    include-message: always

#sonar:
#  java:
#    coveragePlugin: jacoco
#  dynamicAnalysis: reuseReports
#  jacoco:
#    reportPath: ${project.basedir}/../target/jacoco.exec
#  language: java
