spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopper
    username: postgres
    password: postgres

  jackson:
    serialization:
      indent-output: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always
