spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopper
    username: postgres
    password: postgres

  jackson:
    serialization:
      indent-output: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true

server:
  error:
    include-message: always

sonar:
  java:
    coveragePlugin: jacoco
  dynamicAnalysis: reuseReports
  jacoco:
    reportPath: ${project.basedir}/../target/jacoco.exec
  language: java
