CREATE TABLE IF NOT EXISTS SHOPLIST (
    SHOPLIST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    LIST_NAME VARCHAR(64)

  );

  CREATE TABLE IF NOT EXISTS PRODUCT(
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(64),
    PRODUCT_QUANTITY INT

    );