version: '3.8'
services:
  # Maildev server for testing mailing functionality
#  maildev:
#    container_name: mail_dev
#    image: maildev/maildev
#    ports:
#      - '1080:1080'

  # SonarQube server
  sonar:
    container_name: sonarQube
    image: sonarqube:8.9-community
    depends_on:
      - db
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    ports:
      - '9000:9000'

  # Postgres database for application data
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    hostname: postgres
    container_name: shopper-postgresDB
    environment:
      POSTGRES_DB: 'shopper'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
#    volumes:
#      - shopperData:/var/lib/postgresql/data
#volumes:
#  shopperData:
#    external: true
